CREATE TABLE IF NOT EXISTS Photo (
    PhotoID INTEGER PRIMARY KEY AUTOINCREMENT,
    Image TEXT NOT NULL,
    Datetime TEXT NOT NULL,
    LikesNumber INTEGER NOT NULL,
    CommentsNumber INTEGER NOT NULL,
    AuthorID INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Comment (
    CommentID INTEGER PRIMARY KEY AUTOINCREMENT,
    Text TEXT NOT NULL,
    PhotoID INTEGER NOT NULL,
    AuthorID INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Like (
    LikeID INTEGER PRIMARY KEY AUTOINCREMENT,
    PhotoID INTEGER NOT NULL,
    AuthorID INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Error (
    ErrorID INTEGER PRIMARY KEY AUTOINCREMENT,
    Code TEXT NOT NULL,
    Message TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS User (
    UserID INTEGER PRIMARY KEY AUTOINCREMENT,
    Username TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Profile (
    ProfileID INTEGER PRIMARY KEY AUTOINCREMENT,
    Owner INTEGER NOT NULL,
    PhotoNumber INTEGER NOT NULL,
    FollowedNumbers INTEGER NOT NULL,
    FollowersNumber INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Profile_Photos (
    ProfileID INTEGER NOT NULL,
    PhotoID INTEGER NOT NULL,
    FOREIGN KEY (ProfileID) REFERENCES Profile(ProfileID),
    FOREIGN KEY (PhotoID) REFERENCES Photo(PhotoID)
);

CREATE TABLE IF NOT EXISTS Profile_Followers (
    ProfileID INTEGER NOT NULL,
    FollowerID INTEGER NOT NULL,
    FOREIGN KEY (ProfileID) REFERENCES Profile(ProfileID),
    FOREIGN KEY (FollowerID) REFERENCES User(UserID)
);

CREATE TABLE IF NOT EXISTS Profile_Followed (
    ProfileID INTEGER NOT NULL,
    FollowedID INTEGER NOT NULL,
    FOREIGN KEY (ProfileID) REFERENCES Profile(ProfileID),
    FOREIGN KEY (FollowedID) REFERENCES User(UserID)
);

